"""The run plan: which command collects which piece of evidence, on which hosts, in which order.

`accept plan hosts.txt` prints a shell script for an operator to review and run. The commands are the
usual tools for each stage; they are not run anywhere in this lab (there is no GPU in CI), so check
flags against your installed versions before using the script.
"""

from __future__ import annotations

from acceptance.criteria import Criteria

NODE_STAGES = [
    ("inventory", "15 min", [
        "nvidia-smi --query-gpu=index,name,serial,uuid,vbios_version,driver_version --format=csv,noheader > gpus.csv",
        "ibstat > ibstat.txt",
        "perfquery -x > perfquery.txt   # symbol errors and link-downed counters per port",
        "# convert to inventory.json (format in docs/evidence.md)",
    ]),
    ("diag", "about 1 h at level 3", ["dcgmi diag -r {level} -j > dcgm-diag.json"]),
    ("nccl-node", "10 min", ["all_reduce_perf -b 8 -e 8G -f 2 -g {gpus} > nccl-allreduce.txt"]),
]


def render(hosts: list[str], c: Criteria) -> str:
    if not hosts:
        raise ValueError("no hosts given")
    level, gpus = c["diag"]["level"], c["inventory"]["gpus_per_node"]
    racks: dict[str, list[str]] = {}
    for h in hosts:
        racks.setdefault(h.split("-")[0], []).append(h)
    out = ["#!/usr/bin/env bash",
           f"# Acceptance run plan for {c['cluster']['name']}: {len(hosts)} nodes in {len(racks)} racks.",
           "# Generated by `accept plan`. Not tested on real hardware: review every command first.",
           "# Evidence layout expected by `accept evaluate`: evidence/nodes/<host>/..., evidence/racks/<rack>/...",
           "set -euo pipefail", 'EVIDENCE=${EVIDENCE:-evidence}', ""]
    for stage, duration, cmds in NODE_STAGES:
        out.append(f"# --- stage {stage} (every node in parallel, {duration}) ---")
        for h in hosts:
            for cmd in cmds:
                if cmd.startswith("#"):
                    out.append(f"#   {h}: {cmd[2:]}")
                    continue
                cmd = cmd.format(level=level, gpus=gpus)
                file = cmd.split("> ")[-1].split()[0] if "> " in cmd else ""
                remote = cmd.split(" > ")[0]
                out.append(f'mkdir -p "$EVIDENCE/nodes/{h}" && ssh {h} \'{remote}\' > "$EVIDENCE/nodes/{h}/{file}"')
        out.append("")
    out.append("# --- stage nccl-rack (one rack at a time, only nodes that passed stages 1-3) ---")
    out.append("# Edit each host list to drop nodes that failed earlier stages, then run:")
    for rack, members in racks.items():
        hl = ",".join(f"{h}:{gpus}" for h in members)
        out.append(f'mkdir -p "$EVIDENCE/racks/{rack}" && mpirun -np {len(members) * gpus} -H {hl} '
                   f'all_reduce_perf -b 8 -e 8G -f 2 -g 1 > "$EVIDENCE/racks/{rack}/nccl-allreduce.txt"')
    out += ["", f"# --- stage burnin ({c['burnin']['hours']} h, racks that passed) ---",
            "# Run the agreed burn-in workload as one job across all accepted nodes, logging job events in the",
            "# format of docs/evidence.md to $EVIDENCE/burnin-job.jsonl, and hourly per-GPU telemetry",
            "# (temperature, throttling, ECC, XIDs, workload iterations) to $EVIDENCE/nodes/<host>/burnin.jsonl.",
            "# dcgmi dmon and the kernel log are the usual sources for the telemetry.", ""]
    return "\n".join(out) + "\n"
