"""Generates the evidence a real acceptance run would collect, for a fictional cluster:
4 racks x 8 nodes x 8 GPUs (256 GPUs). Nothing here comes from real hardware.

Round 1 has defects of the kinds acceptance testing exists to find:

    r01-n03  VBIOS not on the baseline                       -> firmware, retest
    r01-n08  XID 79 (GPU fell off the bus) on day 2 of burn-in -> RMA
    r02-n01  correctable ECC errors growing, below the limit   -> accepted with an observation
    r02-n05  GPU 3 fails the DCGM memory test                  -> RMA
    r02-n07  only 7 GPUs visible                               -> RMA
    r03-n02  single-node all_reduce at 310 GB/s (NVLink)       -> investigate
    r03-n06  92 °C and thermal throttling during burn-in       -> facility
    r04-n06  InfiniBand port with symbol errors; rack r04 all_reduce at 250 GB/s -> fabric

Round 2 retests what was fixed and reruns the rack tests with those nodes back in. r02-n05's
replacement GPU has not arrived, so it stays out.
"""

from __future__ import annotations

import json
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

RACKS, NODES_PER_RACK, GPUS = 4, 8, 8
MODEL, DRIVER, VBIOS = "LAB-GPU-80GB", "lab-570.1", "LAB-96.00.A1"
START = {1: datetime(2026, 9, 7, tzinfo=timezone.utc), 2: datetime(2026, 9, 16, tzinfo=timezone.utc)}

ROUND1_RETEST = ["r01-n03", "r01-n08", "r02-n07", "r03-n02", "r03-n06",
                 "r04-n01", "r04-n02", "r04-n03", "r04-n04", "r04-n05", "r04-n06", "r04-n07", "r04-n08"]


def node_names() -> list[str]:
    return [f"r{r:02d}-n{n:02d}" for r in range(1, RACKS + 1) for n in range(1, NODES_PER_RACK + 1)]


def generate(out: str | Path, round_: int = 1, seed: int = 7) -> Path:
    out = Path(out)
    rng = random.Random(seed * 10 + round_)
    names = node_names() if round_ == 1 else ROUND1_RETEST
    defects = DEFECTS_R1 if round_ == 1 else {}
    start = START[round_]

    for name in names:
        d = out / "nodes" / name
        d.mkdir(parents=True, exist_ok=True)
        df = defects.get(name, {})
        _write_json(d / "inventory.json", _inventory(name, df, rng))
        if df.get("stop") == "inventory":
            continue
        _write_json(d / "dcgm-diag.json", _diag(df))
        if df.get("stop") == "diag":
            continue
        (d / "nccl-allreduce.txt").write_text(_nccl([name], GPUS, df.get("node_busbw", rng.uniform(462, 478)), rng))
        if df.get("stop") == "nccl-node" or (round_ == 1 and name.startswith("r04")):
            continue  # rack r04 fails its rack test in round 1, so nothing there is burned in
        (d / "burnin.jsonl").write_text(_burnin(df, rng))

    # Round 2 reruns every rack test, because retested nodes rejoin their racks.
    racks = {}
    for name in node_names():
        racks.setdefault(name[:3], []).append(name)
    for rack, members in racks.items():
        if round_ == 1:
            ok = [n for n in members if not defects.get(n, {}).get("stop")]
        else:
            ok = [n for n in members if n != "r02-n05"]
        bw = 250.0 if (round_ == 1 and rack == "r04") else rng.uniform(352, 366)
        p = out / "racks" / rack
        p.mkdir(parents=True, exist_ok=True)
        (p / "nccl-allreduce.txt").write_text(_nccl(ok, GPUS * len(ok), bw, rng))

    if round_ == 1:
        job_nodes = [n for n in node_names() if not n.startswith("r04") and not defects.get(n, {}).get("stop")]
        interrupts = [(30.4, "gpu_xid79", "r01-n08", 3), (51.2, "software_crash", None, 1)]
    else:
        job_nodes = [n for n in node_names() if n != "r02-n05"]
        interrupts = [(44.7, "collective_hang", None, 10), (63.1, "software_crash", None, 1)]
    (out / "burnin-job.jsonl").write_text(_job(job_nodes, start + timedelta(days=1), 72, interrupts))
    _write_json(out / "manifest.json", {
        "cluster": "lab-cluster-a", "round": round_, "started": start.isoformat(),
        "finished": (start + timedelta(days=4, hours=2)).isoformat(),
        "nodes": names, "note": "fictional evidence generated by acceptance.sim"})
    return out


DEFECTS_R1 = {
    "r01-n03": {"vbios": {4: "LAB-96.00.9F"}, "stop": "inventory"},
    "r01-n08": {"xid": (30, 5, 79)},
    "r02-n01": {"sbe": (2, 37)},
    "r02-n05": {"diag_fail": (3, "Memory", "uncorrectable ECC error during the memory test"), "stop": "diag"},
    "r02-n07": {"gpus": 7, "stop": "inventory"},
    "r03-n02": {"node_busbw": 310.0, "stop": "nccl-node"},
    "r03-n06": {"hot": True},
    "r04-n06": {"ib_errors": ("mlx5_3", 1843)},
}


def _inventory(name: str, df: dict, rng: random.Random) -> dict:
    n_gpus = df.get("gpus", GPUS)
    gpus = [{"index": i, "model": MODEL, "vbios": df.get("vbios", {}).get(i, VBIOS),
             "serial": f"LAB{rng.randrange(10**9, 10**10)}", "uuid": f"GPU-lab-{name}-{i}"} for i in range(n_gpus)]
    ports = [{"name": f"mlx5_{i}", "state": "Active", "rate_gbps": 400, "symbol_errors": 0, "link_downed": 0}
             for i in range(8)]
    if "ib_errors" in df:
        port, n = df["ib_errors"]
        next(p for p in ports if p["name"] == port)["symbol_errors"] = n
    return {"hostname": name, "rack": name[:3], "driver_version": DRIVER, "os": "lab-linux-24.04", "gpus": gpus,
            "ib_ports": ports, "collected_with": "nvidia-smi -q, ibstat, perfquery (lab: generated)"}


TESTS = [("Deployment", ["Software"]), ("Integration", ["PCIe"]), ("Hardware", ["Memory", "Diagnostic"]),
         ("Stress", ["Memory Bandwidth", "Targeted Stress", "Targeted Power"])]


def _diag(df: dict) -> dict:
    """Modelled on the shape of `dcgmi diag -r 3 -j`; field names vary between DCGM versions."""
    fail = df.get("diag_fail")
    cats = []
    for cat, tests in TESTS:
        ts = []
        for t in tests:
            if t == "Software":
                results = [{"status": "Pass"}]
            else:
                results = []
                for g in range(GPUS):
                    r = {"gpu_id": str(g), "status": "Pass"}
                    if fail and fail[0] == g and fail[1] == t:
                        r = {"gpu_id": str(g), "status": "Fail", "warnings": [{"warning": fail[2]}]}
                    results.append(r)
            ts.append({"name": t, "results": results})
        cats.append({"category": cat, "tests": ts})
    return {"DCGM GPU Diagnostic": {"test_categories": cats}, "Driver Version Detected": DRIVER,
            "note": "lab sample, not produced by DCGM"}


def _nccl(hosts: list[str], ranks: int, peak_busbw: float, rng: random.Random) -> str:
    """Text in the format of nccl-tests all_reduce_perf (-b 8 -e 8G -f 2)."""
    lines = [f"# nThread 1 nGpus 1 minBytes 8 maxBytes 8589934592 step: 2(factor) warmup iters: 5 iters: 20 "
             f"agg iters: 1 validation: 1 graph: 0", "#", "# Using devices"]
    r = 0
    per_host = max(1, ranks // max(1, len(hosts)))
    for h in hosts:
        for dev in range(per_host):
            lines.append(f"#  Rank {r:2d} Group  0 Pid {40000 + r:6d} on {h:>10} device  {dev} [0x{dev * 16 + 24:02x}] {MODEL}")
            r += 1
    lines += ["#",
              "#                                                              out-of-place                       in-place          ",
              "#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong",
              "#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       "]
    factor = 2 * (r - 1) / r if r > 1 else 1.0
    size, busbws = 8, []
    while size <= 8 * 1024 ** 3:
        frac = size / (size + 32 * 1024 ** 2)  # small messages are latency-bound
        busbw = peak_busbw * frac * rng.uniform(0.99, 1.01)
        algbw = busbw / factor
        t_us = max(size / (algbw * 1e3), 8.0) if algbw > 0 else 8.0
        busbw = size / t_us / 1e3 * factor
        algbw = busbw / factor
        busbws.append(busbw)
        row = (f"{size:>12d}  {size // 4:>12d}     float     sum      -1  {t_us:7.1f}  {algbw:6.2f}  {busbw:6.2f}      0"
               f"  {t_us * 0.99:7.1f}  {algbw * 1.01:6.2f}  {busbw * 1.01:6.2f}      0")
        lines.append(row)
        size *= 2
    lines += ["# Out of bounds values : 0 OK", f"# Avg bus bandwidth    : {sum(busbws) / len(busbws):.3f} ", "#"]
    return "\n".join(lines) + "\n"


def _burnin(df: dict, rng: random.Random, hours: int = 72) -> str:
    out = []
    for h in range(hours):
        for g in range(GPUS):
            hot = df.get("hot") and g in (2, 3)
            temp = rng.uniform(88, 92) if hot and h % 2 == 0 else rng.uniform(62, 79)
            row = {"hour": h, "gpu": g, "max_temp_c": round(temp, 1),
                   "thermal_throttle_s": round(rng.uniform(300, 700)) if hot and h % 2 == 0 else 0,
                   "sbe": 0, "dbe": 0, "xid": [], "iterations": 60, "failures": 0}
            if "sbe" in df and g == df["sbe"][0] and h % 2 == 0 and h < df["sbe"][1] * 2:
                row["sbe"] = 1
            if "xid" in df and (h, g) == df["xid"][:2]:
                row["xid"], row["failures"] = [df["xid"][2]], 1
            out.append(json.dumps(row))
    return "\n".join(out) + "\n"


def _job(nodes: list[str], start: datetime, hours: int, interrupts) -> str:
    """Burn-in job log in the event format of repo 12: hourly checkpoints of 2 minutes."""
    def ev(t: float, event: str, **extra):
        stamp = (start + timedelta(hours=t)).strftime("%Y-%m-%dT%H:%M:%SZ")
        return json.dumps({"time": stamp, "job": "burnin", "event": event, **extra})

    lines = [ev(0, "start", nodes=len(nodes), gpus_per_node=GPUS)]
    t, queue = 0.0, sorted(interrupts)
    while t < hours:
        nxt = t + 1.0
        if queue and queue[0][0] < min(nxt, hours):
            at, cause, node, detect = queue.pop(0)
            lines.append(ev(at, "interrupt", cause=cause, **({"node": node} if node else {})))
            lines.append(ev(at + detect / 60, "detected"))
            lines.append(ev(at + detect / 60 + 5 / 60, "nodes_ready"))
            t = at + detect / 60 + 5 / 60 + 15 / 60
            lines.append(ev(t, "running"))
            continue
        if nxt >= hours:
            break
        lines.append(ev(nxt, "checkpoint_start"))
        lines.append(ev(nxt + 2 / 60, "checkpoint_end"))
        t = nxt + 2 / 60
    lines.append(ev(hours, "end"))
    return "\n".join(lines) + "\n"


def _write_json(p: Path, d: dict) -> None:
    p.write_text(json.dumps(d, indent=2) + "\n")
